package com.lms.stepdefinitions;

import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;


public class LoginSteps {


    @Given("Admin creates request with valid credentials")
    public void adminCreatesRequestWithValidCredentials() {

    }

    @When("Admin calls Post Https method  with valid endpoint")
    public void adminCallsPostHttpsMethodWithValidEndpoint() {

    }

    @Then("Admin receives {int} created with auto generated token")
    public void adminReceivesCreatedWithAutoGeneratedToken(int arg0) {
    }
}
